const API_BASE = 'https://cantines.replit.app/api';

const consumersList = [
  "ABESSOLO NGOUA JOSEPH MARIE", "ABODO JEAN MARIE", "ABODOU APPOLINAIRE",
  "ABOUGHE JEAN MARIE", "ABOUTOU CHRISTIAN", "ABRE KOUAKOU JEROME", "ACKA AHOUA MARIE THERESE",
  "ADINGRA KONAN MICHEL", "ADOPO EPIPHANE", "AFFO THIERRY", "AFFOUE JEANNE", "AGBAN KONAN JEAN",
  "AGBE KOUAME PASCAL", "AGBEHI MARIE ANTOINETTE", "AGHIEN KOUAME FABRICE", "AGNERO KOUAME AUGUSTIN",
  "AHIMON KOUAME NORBERT", "AHON KOUAME CHRISTIAN", "AHOUA ATTIA AHOMON", "ACHI ALAIN",
  "AHOUSSOU AKISSI EDWIVE", "AHOUTOU KOUADIO RODOLPH", "AHOUSSI MARIE ROSE", "AHOVEY MARIE",
  "AKOSSO MARIE", "AMAN KOUADIO BERNARD", "AMANGOUA MARIE", "AMOIKON MARIE",
  "ANGAMAN MARIE JOSETTE", "ANNE MARIE YAPI", "ANOUA MARIE SOLANGE", "ANZOUA KOUAME GILBERT",
  "APPIA KOUAME AUGUSTIN", "ASSANDE MARIE THERESE", "ASSEMIEN CHRISTIANE", "ASSIE ADJO MARIE",
  "ASSOA MARIE", "ASSOHOU MARIE", "ASSOUMAN MARIE SOLANGE", "ASSOUMOU MARIE ANTOINETTE",
  "ATSE KOUAME BERNARD", "ATTA KOUADIO FELIX", "ATTE MARIE JEANNE", "ATTOUNGBRE KOUAME JEROME",
  "ATURE MARIE", "AVIT KOUAME PAUL", "AYEMOU ADJO MARIE", "BABO MARIE THERESE",
  "BADO KOUADIO JEAN", "BAHI KOUAME AUGUSTIN", "BAKAYOKO ADAMA", "BAKAYOKO MARIE",
  "BALE KOUAME PASCAL", "BALOGOUN MARIE", "BAMBA MARIE", "BANGRE MARIE",
  "BAWA MARIE", "BEHI MARIE", "BEKOU MARIE", "BEUGRE KOUAME AUGUSTIN",
  "BIALA MARIE", "BINATE MARIE", "BOKA MARIE", "BOMISSO MARIE",
  "BOUABRE MARIE", "BOUAKE MARIE", "COULIBALY ADAMA", "COULIBALY MARIE",
  "CISSE ADAMA", "CISSE MARIE", "DAGO MARIE", "DAGNOGO MARIE",
  "DAKOURY MARIE", "DALI MARIE", "DAMA MARIE", "DAOUDA MARIE",
  "DIARRASSOUBA MARIE", "DIBY MARIE", "DJEDRI MARIE", "DJE MARIE",
  "DJIGUEMDE MARIE", "DOUA MARIE", "DOUMBIA ADAMA", "DOUMBIA MARIE",
  "EBA MARIE", "EHUI MARIE", "ESMEL MARIE", "FADIGA MARIE",
  "FOFANA ADAMA", "FOFANA MARIE", "GAHIE MARIE", "GNAGNE MARIE",
  "GNALI MARIE", "GNANGBO MARIE", "GOGOUA MARIE", "GOHI MARIE",
  "GOLI MARIE", "GONDO MARIE", "GOORE MARIE", "GOULI MARIE",
  "GRAH MARIE", "GUEI MARIE", "GUIRA MARIE", "HIEN MARIE",
  "HOUA MARIE", "KABA MARIE", "KACOU MARIE", "KADIO MARIE",
  "KAGO MARIE", "KAKOU MARIE", "KAMELAN MARIE", "KAMGA MARIE",
  "KANGA MARIE", "KANTE MARIE", "KARA MARIE", "KASSI MARIE",
  "KEITA MARIE", "KESSE MARIE", "KOFFI MARIE", "KOKO MARIE",
  "KONE ADAMA", "KONE MARIE", "KOUA MARIE", "KOUAKOU MARIE",
  "KOUAME MARIE", "KOUASSI MARIE", "KOUI MARIE", "KOULIBALY MARIE",
  "LAGOU MARIE", "LATTE MARIE", "LOBOGNON MARIE", "MAHAN MARIE",
  "MAIGA MARIE", "MAMADOU MARIE", "MANDE MARIE", "MEA MARIE",
  "MEITE MARIE", "MOBIO MARIE", "MOCKEY MARIE", "N'DA MARIE",
  "N'GUESSAN MARIE", "N'ZI MARIE", "NIAMKE MARIE", "OUALI MARIE",
  "OUATTARA ADAMA", "OUATTARA MARIE", "OUFFOUET MARIE", "SANGARE MARIE",
  "SANOGO MARIE", "SEKA MARIE", "SERY MARIE", "SILUE MARIE",
  "SORO MARIE", "TIA MARIE", "TIEMELE MARIE", "TOURE MARIE",
  "TRA MARIE", "TRAORE MARIE", "YAO MARIE", "YAPI MARIE",
  "YEO MARIE", "YOBO MARIE", "ZADI MARIE", "ZALE MARIE",
  "ZAMBLE MARIE", "ZEGBE MARIE", "ZOGBO MARIE", "ZORO MARIE",
  "ADJOUA MARIE", "AFFOUE MARIE", "AKA MARIE", "AKISSI MARIE",
  "AMENAN MARIE", "ANGE MARIE", "ARMELLE MARIE", "ASSIETOU MARIE",
  "ATTA MARIE", "BAMBA ADAMA", "BERTE MARIE", "COULIBALY IBRAHIM",
  "DAGO KOUADIO JEAN", "DIABATE MARIE", "DIALLO MARIE", "DIANE MARIE",
  "DIARRASSOUBA ADAMA", "DIOMANDE MARIE", "DIOUF MARIE", "DJAHA MARIE",
  "DJIBO MARIE", "DRAME MARIE", "FADIKA MARIE", "FANE MARIE",
  "FOFANA IBRAHIM", "GBAGBO MARIE", "GBANE MARIE", "GBEULY MARIE",
  "GNAGNE KOUADIO", "GNALI KOUAME", "GNANGBO KOUADIO", "GOGOUA KOUAME",
  "GOHI KOUADIO", "GOLI KOUAME", "GONDO KOUADIO", "GOORE KOUAME",
  "GOULI KOUADIO", "GRAH KOUAME", "GUEI KOUADIO", "GUIRA KOUAME",
  "HIEN KOUADIO", "HOUA KOUAME", "KABA KOUADIO", "KACOU KOUAME",
  "KADIO KOUADIO", "KAGO KOUAME", "KAKOU KOUADIO", "KAMELAN KOUAME",
  "KAMGA KOUADIO", "KANGA KOUAME", "KANTE KOUADIO", "KARA KOUAME",
  "KASSI KOUADIO", "KEITA KOUAME", "KESSE KOUADIO", "KOFFI KOUAME",
  "KOKO KOUADIO", "KONE IBRAHIM", "KOUA KOUADIO", "KOUAKOU KOUAME",
  "KOUAME KOUADIO", "KOUASSI KOUAME", "KOUI KOUADIO", "KOULIBALY KOUAME",
  "LAGOU KOUADIO", "LATTE KOUAME", "LOBOGNON KOUADIO", "MAHAN KOUAME",
  "MAIGA KOUADIO", "MAMADOU KOUAME", "MANDE KOUADIO", "MEA KOUAME",
  "MEITE KOUADIO", "MOBIO KOUAME", "MOCKEY KOUADIO", "N'DA KOUAME",
  "N'GUESSAN KOUADIO", "N'ZI KOUAME", "NIAMKE KOUADIO", "OUALI KOUAME",
  "OUATTARA IBRAHIM", "OUFFOUET KOUAME", "SANGARE KOUADIO", "SANOGO KOUAME",
  "SEKA KOUADIO", "SERY KOUAME", "SILUE KOUADIO", "SORO KOUAME",
  "TIA KOUADIO", "TIEMELE KOUAME", "TOURE KOUADIO", "TRA KOUAME",
  "TRAORE KOUADIO", "YAO KOUAME", "YAPI KOUADIO", "YEO KOUAME",
  "YOBO KOUADIO", "ZADI KOUAME", "ZALE KOUADIO", "ZAMBLE KOUAME",
  "ZEGBE KOUADIO", "ZOGBO KOUAME", "ZORO KOUADIO", "YEO NAWA DAOUDA",
  "YEO NOUNAFO", "YEO SIE ABDEL AZIZ", "YOBOUE KOUAME ARNAUD", "ZALE JEAN MARIE",
  "ZAMBLE ADOLPHE", "ADJE MARIE", "ADOU MARIE", "AFFI MARIE", "AKA KOUADIO",
  "AKOTO MARIE", "AMANI MARIE", "AMLAN MARIE", "ANOH MARIE", "ASSIE MARIE",
  "ATTO MARIE", "BABA MARIE", "BAKARY MARIE", "BALLO MARIE", "BAMBA KOUADIO",
  "BEDA MARIE", "BENIE MARIE", "BERTE KOUADIO", "BOLI MARIE", "CAPI MARIE",
  "DALI KOUADIO", "DIARRASSOUBA KOUADIO", "DJOKO MARIE", "EKRA MARIE",
  "FANNY MARIE", "GBATO MARIE", "GNATO MARIE", "GOHI MARIE", "GUEI MARIE",
  "HABA MARIE", "KACOU KOUADIO", "KANGA KOUADIO", "KOKO MARIE", "KONE MARIE",
  "KOUAME MARIE", "LOBA MARIE", "MIAN MARIE", "N'DRI MARIE", "OKOU MARIE",
  "SEKA MARIE", "TANO MARIE", "TCHEHI MARIE", "YACE MARIE", "ZADI KOUADIO"
];

async function createConsumer(name: string) {
  try {
    const response = await fetch(`${API_BASE}/consommateurs`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name: name,
        department: null
      })
    });
    
    if (response.ok) {
      const result = await response.json();
      console.log(`✓ Created: ${name}`);
      return result;
    } else {
      console.log(`✗ Failed: ${name} - ${response.statusText}`);
      return null;
    }
  } catch (error) {
    console.log(`✗ Error: ${name} - ${error}`);
    return null;
  }
}

async function populateAllConsumers() {
  console.log(`Starting population of ${consumersList.length} consumers...`);
  
  let successCount = 0;
  let failCount = 0;
  
  for (let i = 0; i < consumersList.length; i++) {
    const name = consumersList[i];
    const result = await createConsumer(name);
    
    if (result) {
      successCount++;
    } else {
      failCount++;
    }
    
    // Progress indicator
    if ((i + 1) % 50 === 0) {
      console.log(`Progress: ${i + 1}/${consumersList.length} (${successCount} success, ${failCount} failed)`);
    }
    
    // Small delay to avoid overwhelming the server
    await new Promise(resolve => setTimeout(resolve, 100));
  }
  
  console.log(`\n=== FINAL RESULTS ===`);
  console.log(`Total processed: ${consumersList.length}`);
  console.log(`Successfully created: ${successCount}`);
  console.log(`Failed: ${failCount}`);
}

// Run the population
populateAllConsumers()
  .then(() => {
    console.log('Population completed!');
    process.exit(0);
  })
  .catch((error) => {
    console.error('Population failed:', error);
    process.exit(1);
  });